package com.bookstore;

import com.bookstore.service.BookstoreService;
import org.springframework.boot.ApplicationRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

@SpringBootApplication
public class MainApplication {

    private final BookstoreService bookstoreService;

    public MainApplication(BookstoreService bookstoreService) {
        this.bookstoreService = bookstoreService;
    }

    public static void main(String[] args) {
        SpringApplication.run(MainApplication.class, args);
    }

    @Bean
    public ApplicationRunner init() {
        return args -> {
            bookstoreService.insertAuthorGetAutoGeneratedKeyViaJdbcTemplate();
            bookstoreService.insertAuthorGetAutoGeneratedKeyViaSimpleJdbcInsert();
            bookstoreService.insertAuthorGetAutoGeneratedKeyViaGetId();
        };
    }
}

/*
 * 
 * How To Obtain Auto-Generated Keys

Description: This application is an example of retrieving the database auto-generated primary keys.

Key points:

JPA style, retrieve the auto-generated keys via getId()
JDBC style, retrieve the auto-generated keys via JdbcTemplate
JDBC style, retrieve the auto-generated keys via SimpleJdbcInsert

 * 
 * 
 */
